// SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// This file is automatically generated, so please do not edit it.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for French (`fr`).
class AppLocalizationsFr extends AppLocalizations {
  AppLocalizationsFr([String locale = 'fr']) : super(locale);

  @override
  String get appTitle => 'Air';

  @override
  String get userSettingsScreen_title => 'Paramètres utilisateur';

  @override
  String get userSettingsScreen_idCopied =>
      'ID utilisateur copié dans le presse-papiers';

  @override
  String get userSettingsScreen_profileDescription =>
      'Les autres verront votre photo et votre nom lorsque vous communiquez avec eux.';

  @override
  String get userSettingsScreen_userNamesDescription =>
      'Partagez des noms d\'utilisateur avec d\'autres pour qu\'ils puissent se connecter avec vous. Après la connexion, les noms d\'utilisateur ne sont plus visibles aux autres. Vous pouvez avoir jusqu\'à 5 noms d\'utilisateur.';

  @override
  String get userSettingsScreen_interfaceScale => 'Échelle de l\'interface';

  @override
  String get userSettingsScreen_help => 'Aide';

  @override
  String get removeUsernameDialog_title => 'Supprimer le nom d\'utilisateur';

  @override
  String get removeUsernameDialog_content =>
      'Si vous continuez, votre nom d\'utilisateur sera supprimé et pourra être réclamé par quelqu\'un d\'autre. Vous ne serez plus accessible par son intermédiaire.';

  @override
  String get removeUsernameDialog_cancel => 'Annuler';

  @override
  String get removeUsernameDialog_remove => 'Supprimer';

  @override
  String get userSettingsScreen_noUserHandles => 'aucun pseudo pour le moment';

  @override
  String get userSettingsScreen_userHandlePlaceholder => 'Nom d\'utilisateur';

  @override
  String get addMembersScreen_title => 'Ajouter des membres';

  @override
  String get addMembersScreen_addMembers => 'Ajouter membre(s)';

  @override
  String get addMembersScreen_error_noActiveConversation =>
      'une conversation active est obligatoire';

  @override
  String get conversationDetailsScreen_title => 'Détails';

  @override
  String get conversationDetailsScreen_unknownConversation =>
      'Conversation inconnue';

  @override
  String get conversationScreen_emptyConversation =>
      'Sélectionnez une conversation pour commencer à envoyer des messages';

  @override
  String get memberDetailsScreen_title => 'Détails du membre';

  @override
  String get removeUserDialog_title => 'Retirer l\'utilisateur';

  @override
  String get removeUserDialog_content =>
      'Êtes-vous sûr de vouloir retirer cet utilisateur du groupe ?';

  @override
  String get removeUserDialog_cancel => 'Annuler';

  @override
  String get removeUserDialog_removeUser => 'Retirer l\'utilisateur';

  @override
  String get removeUserButton_text => 'Retirer l\'utilisateur';

  @override
  String get deleteConnectionButton_text => 'Delete Connection';

  @override
  String get deleteConnectionDialog_title => 'Delete Connection';

  @override
  String get deleteConnectionDialog_content =>
      'Are you sure you want to delete this connection? The message history will be also deleted.';

  @override
  String get deleteConnectionDialog_cancel => 'Cancel';

  @override
  String get deleteConnectionDialog_delete => 'Delete';

  @override
  String get introScreen_signUp => 'S\'inscrire';

  @override
  String get userHandleScreen_title => 'Nom d\'utilisateur';

  @override
  String get userHandleScreen_inputHint => 'Nom d\'utilisateur';

  @override
  String get userHandleScreen_error_emptyHandle =>
      'Le nom d\'utilisateur ne peut pas être vide';

  @override
  String get userHandleScreen_description =>
      'Choisissez un nom d\'utilisateur que d\'autres peuvent utiliser pour se connecter avec vous.\n\nUtilisez des lettres, des chiffres ou des traits de soulignement. Minimum 5 caractères.';

  @override
  String get userHandleScreen_save => 'Enregistrer';

  @override
  String get editDisplayNameScreen_title => 'Nom d\'affichage';

  @override
  String get editDisplayNameScreen_hintText => 'Nom d\'affichage';

  @override
  String get editDisplayNameScreen_description =>
      'Choisissez un nom que les autres verront lorsque vous communiquez avec eux.';

  @override
  String get editDisplayNameScreen_save => 'Enregistrer';

  @override
  String get systemMessage_userAddedUser_prefix => '';

  @override
  String get systemMessage_userAddedUser_infix => ' a ajouté ';

  @override
  String get systemMessage_userAddedUser_suffix => '';

  @override
  String get systemMessage_userRemovedUser_prefix => '';

  @override
  String get systemMessage_userRemovedUser_infix => ' a retiré ';

  @override
  String get systemMessage_userRemovedUser_suffix => '';

  @override
  String get timestamp_now => 'Maintenant';

  @override
  String get timestamp_yesterday => 'Hier';

  @override
  String get conversationList_newContact => 'Nouveau contact';

  @override
  String get conversationList_newGroup => 'Nouveau groupe';

  @override
  String get conversationList_emptyMessage =>
      'Créez une nouvelle connexion pour commencer';

  @override
  String get conversationList_draft => 'Brouillon';

  @override
  String get conversationList_you => 'Vous';

  @override
  String get conversationList_imageEmoji => '🖼️';

  @override
  String get conversationList_fileEmoji => '📎';

  @override
  String get settings_profile => 'Profil';

  @override
  String get settings_developerSettings => 'Paramètres (développeur)';

  @override
  String get newConversationDialog_newConversationTitle =>
      'Nouvelle conversation';

  @override
  String get newConversationDialog_newConversationDescription =>
      'Choisissez un nom pour la nouvelle conversation';

  @override
  String get newConversationDialog_conversationNamePlaceholder =>
      'Nom de la conversation';

  @override
  String get newConversationDialog_actionButton => 'Créer une conversation';

  @override
  String newConversationDialog_error(Object conversationName) {
    return 'Impossible d\'ajouter une conversation avec le nom $conversationName';
  }

  @override
  String get newConversationDialog_error_emptyGroupName =>
      'Le nom de la conversation ne peut pas être vide';

  @override
  String get newConnectionDialog_newConnectionTitle => 'Nouvelle connexion';

  @override
  String get newConnectionDialog_newConnectionDescription =>
      'Saisissez le pseudo de l\'utilisateur avec lequel vous souhaitez vous connecter';

  @override
  String get newConnectionDialog_usernamePlaceholder => 'Nom d\'utilisateur';

  @override
  String get newConnectionDialog_actionButton => 'Se connecter';

  @override
  String newConnectionDialog_error(Object username) {
    return 'Impossible d\'ajouter l\'utilisateur avec le pseudo $username. Veuillez réessayer.';
  }

  @override
  String get newConnectionDialog_error_emptyHandle =>
      'Le pseudo ne peut pas être vide';

  @override
  String newConnectionDialog_error_handleNotFound(Object username) {
    return 'Le pseudo $username n\'existe pas';
  }

  @override
  String composer_inputHint(Object conversationTitle) {
    return 'Message à $conversationTitle';
  }

  @override
  String get composer_editMessage => 'Modifier le message';

  @override
  String get composer_error_attachment =>
      'Échec du téléchargement de la pièce jointe. Veuillez réessayer.';

  @override
  String attachmentSize(double size, Object byteUnit) {
    final intl.NumberFormat sizeNumberFormat = intl
        .NumberFormat.decimalPatternDigits(
      locale: localeName,
      decimalDigits: 2,
    );
    final String sizeString = sizeNumberFormat.format(size);

    return '$sizeString $byteUnit';
  }

  @override
  String get textMessage_edited => 'modifié';

  @override
  String get reportSpamButton_text => 'Signaler comme spam';

  @override
  String get reportSpamDialog_title => 'Signaler comme spam ?';

  @override
  String get reportSpamDialog_content =>
      'Air sera averti que cette personne peut envoyer des spams. Air ne peut jamais voir le contenu des chats.';

  @override
  String get reportSpamDialog_cancel => 'Annuler';

  @override
  String get reportSpamDialog_reportSpam => 'Signaler comme spam';

  @override
  String get reportSpamDialog_success => 'Spam signalé';

  @override
  String get reportSpamDialog_error =>
      'Impossible de signaler le spam. Veuillez réessayer.';

  @override
  String get helpScreen_title => 'Aide';

  @override
  String get helpScreen_contactUs => 'Nous contacter';

  @override
  String get helpScreen_versionInfo => 'Informations sur la version';

  @override
  String get helpScreen_licenses => 'Licences';

  @override
  String get licensesScreen_title => 'Licences';

  @override
  String get contactUsScreen_title => 'Contact';

  @override
  String get contactUsScreen_subject => 'Objet du message';

  @override
  String get contactUsScreen_body => 'Corps du message';

  @override
  String get contactUsScreen_composeEmail => 'Composer un e-mail';

  @override
  String get contactUsScreen_subject_somethingNotWorking =>
      'Quelque chose ne fonctionne pas';

  @override
  String get contactUsScreen_subject_iHaveAQuestion => 'J\'ai une question';

  @override
  String get contactUsScreen_subject_requestFeature =>
      'Demander une fonctionnalité';

  @override
  String get contactUsScreen_subject_other => 'Autre';

  @override
  String get contactUsScreen_subject_empty => 'Veuillez sélectionner un objet';

  @override
  String get contactUsScreen_body_empty => 'Entrez votre message';

  @override
  String get contactUsScreen_body_tooShort =>
      'Veuillez fournir plus d\'informations';

  @override
  String get contactUsScreen_errorLaunchingEmail =>
      'Impossible de lancer le client de messagerie';

  @override
  String get groupDetails_members => 'Members';

  @override
  String get groupDetails_addMembers => 'Add Members';

  @override
  String get groupDetails_leaveConversation => 'Leave Conversation';

  @override
  String get groupDetails_deleteConversation => 'Delete Conversation';

  @override
  String get leaveConversationDialog_title => 'Leave Conversation';

  @override
  String get leaveConversationDialog_content =>
      'Are you sure you want to leave this conversation?';

  @override
  String get leaveConversationDialog_cancel => 'Cancel';

  @override
  String get leaveConversationDialog_leave => 'Leave';

  @override
  String get deleteConversationDialog_title => 'Delete Conversation';

  @override
  String get deleteConversationDialog_content =>
      'Are you sure you want to delete this conversation? The message history will be also deleted.';

  @override
  String get deleteConversationDialog_cancel => 'Cancel';

  @override
  String get deleteConversationDialog_delete => 'Delete';

  @override
  String get byteUnit_B => 'o';

  @override
  String get byteUnit_KB => 'Ko';

  @override
  String get byteUnit_MB => 'Mo';

  @override
  String get byteUnit_GB => 'Go';

  @override
  String get byteUnit_TB => 'To';

  @override
  String get byteUnit_PB => 'Po';

  @override
  String get byteUnit_EB => 'Eo';

  @override
  String get byteUnit_ZB => 'Zo';

  @override
  String get byteUnit_YB => 'Yo';
}
