// SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// This file is automatically generated, so please do not edit it.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'Air';

  @override
  String get userSettingsScreen_title => 'User Settings';

  @override
  String get userSettingsScreen_idCopied => 'User ID copied to clipboard';

  @override
  String get userSettingsScreen_profileDescription =>
      'Others will see your picture and name when you communicate with them.';

  @override
  String get userSettingsScreen_userNamesDescription =>
      'Share usernames with others so they can connect with you. After the connection, usernames are not visible to others anymore. You can have up to 5 usernames.';

  @override
  String get userSettingsScreen_interfaceScale => 'Interface scale';

  @override
  String get userSettingsScreen_help => 'Help';

  @override
  String get removeUsernameDialog_title => 'Remove Username';

  @override
  String get removeUsernameDialog_content =>
      'If you continue, your username will be removed and may be claimed by someone else. You’ll no longer be reachable through it.';

  @override
  String get removeUsernameDialog_cancel => 'Cancel';

  @override
  String get removeUsernameDialog_remove => 'Remove';

  @override
  String get userSettingsScreen_noUserHandles => 'no usernames yet';

  @override
  String get userSettingsScreen_userHandlePlaceholder => 'Username';

  @override
  String get addMembersScreen_title => 'Add members';

  @override
  String get addMembersScreen_addMembers => 'Add member(s)';

  @override
  String get addMembersScreen_error_noActiveChat =>
      'an active chat is obligatory';

  @override
  String get chatDetailsScreen_title => 'Details';

  @override
  String get chatDetailsScreen_unknownChat => 'Unknown chat';

  @override
  String get blockedChatFooter_message =>
      'You have blocked this chat. You will not get any messages, unless you unblock it.';

  @override
  String get blockedChatFooter_delete => 'Delete';

  @override
  String get blockedChatFooter_unblock => 'Unblock';

  @override
  String get chatScreen_emptyChat => 'Select a chat to start messaging';

  @override
  String get memberDetailsScreen_title => 'Member details';

  @override
  String get removeUserDialog_title => 'Remove user';

  @override
  String get removeUserDialog_content =>
      'Are you sure you want to remove this user from the group?';

  @override
  String get removeUserDialog_cancel => 'Cancel';

  @override
  String get removeUserDialog_removeUser => 'Remove User';

  @override
  String get removeUserButton_text => 'Remove User';

  @override
  String get blockConnectionButton_text => 'Block Contact';

  @override
  String get blockConnectionDialog_title => 'Block Contact';

  @override
  String get blockConnectionDialog_content =>
      'Are you sure you want to block this contact? The user will not be able to send messages to you.';

  @override
  String get blockConnectionDialog_cancel => 'Cancel';

  @override
  String get blockConnectionDialog_block => 'Block';

  @override
  String get unblockConnectionButton_text => 'Unblock Contact';

  @override
  String get unblockConnectionDialog_title => 'Unblock Contact';

  @override
  String get unblockConnectionDialog_content =>
      'Are you sure you want to unblock this contact? The user will be able to send messages to you, and your profile will be visible to them.';

  @override
  String get unblockConnectionDialog_cancel => 'Cancel';

  @override
  String get unblockConnectionDialog_unblock => 'Unblock';

  @override
  String get deleteConnectionButton_text => 'Delete Connection';

  @override
  String get deleteConnectionDialog_title => 'Delete Connection';

  @override
  String get deleteConnectionDialog_content =>
      'Are you sure you want to delete this connection? The message history will be also deleted.';

  @override
  String get deleteConnectionDialog_cancel => 'Cancel';

  @override
  String get deleteConnectionDialog_delete => 'Delete';

  @override
  String get introScreen_signUp => 'Sign up';

  @override
  String get userHandleScreen_title => 'Username';

  @override
  String get userHandleScreen_inputHint => 'Username';

  @override
  String get userHandleScreen_error_emptyHandle => 'Username cannot be empty';

  @override
  String get userHandleScreen_error_alreadyExists => 'Username already exists';

  @override
  String get userHandleScreen_description =>
      'Choose a username that others can use to connect with you.\n\nUse letters, numbers, or underscores. Minimum 5 characters.';

  @override
  String get userHandleScreen_save => 'Save';

  @override
  String get editDisplayNameScreen_title => 'Display Name';

  @override
  String get editDisplayNameScreen_hintText => 'Display name';

  @override
  String get editDisplayNameScreen_description =>
      'Choose a name that others will see when you communicate with them.';

  @override
  String get editDisplayNameScreen_save => 'Save';

  @override
  String get systemMessage_userAddedUser_prefix => '';

  @override
  String get systemMessage_userAddedUser_infix => ' added ';

  @override
  String get systemMessage_userAddedUser_suffix => '';

  @override
  String get systemMessage_userRemovedUser_prefix => '';

  @override
  String get systemMessage_userRemovedUser_infix => ' removed ';

  @override
  String get systemMessage_userRemovedUser_suffix => '';

  @override
  String get timestamp_now => 'Now';

  @override
  String get timestamp_yesterday => 'Yesterday';

  @override
  String get chatList_newContact => 'New contact';

  @override
  String get chatList_newGroup => 'New group';

  @override
  String get chatList_emptyMessage => 'Create a new connection to get started';

  @override
  String get chatList_draft => 'Draft';

  @override
  String get chatList_you => 'You';

  @override
  String get chatList_imageEmoji => '🖼️';

  @override
  String get chatList_fileEmoji => '📎';

  @override
  String get chatList_blocked => '🚫 Blocked';

  @override
  String get settings_profile => 'Profile';

  @override
  String get settings_developerSettings => 'Settings (developer)';

  @override
  String get newChatDialog_newChatTitle => 'New chat';

  @override
  String get newChatDialog_newChatDescription =>
      'Choose a name for the new chat';

  @override
  String get newChatDialog_chatNamePlaceholder => 'Chat name';

  @override
  String get newChatDialog_actionButton => 'Create chat';

  @override
  String newChatDialog_error(Object chatName) {
    return 'Failed to add chat with name $chatName';
  }

  @override
  String get newChatDialog_error_emptyGroupName => 'Chat name cannot be empty';

  @override
  String get newConnectionDialog_newConnectionTitle => 'New connection';

  @override
  String get newConnectionDialog_newConnectionDescription =>
      'Enter the username of the user you want to connect to';

  @override
  String get newConnectionDialog_usernamePlaceholder => 'Username';

  @override
  String get newConnectionDialog_actionButton => 'Connect';

  @override
  String newConnectionDialog_error(Object username) {
    return 'Failed to add user with username $username. Please try again.';
  }

  @override
  String get newConnectionDialog_error_emptyHandle =>
      'Username cannot be empty';

  @override
  String newConnectionDialog_error_handleNotFound(Object username) {
    return 'Username $username does not exist';
  }

  @override
  String composer_inputHint(Object chatTitle) {
    return 'Message $chatTitle';
  }

  @override
  String get composer_editMessage => 'Edit Message';

  @override
  String get composer_error_attachment =>
      'Failed to upload attachment. Please try again.';

  @override
  String attachmentSize(double size, Object byteUnit) {
    final intl.NumberFormat sizeNumberFormat = intl
        .NumberFormat.decimalPatternDigits(
      locale: localeName,
      decimalDigits: 2,
    );
    final String sizeString = sizeNumberFormat.format(size);

    return '$sizeString $byteUnit';
  }

  @override
  String get textMessage_edited => 'edited';

  @override
  String get reportSpamButton_text => 'Report Spam';

  @override
  String get reportSpamDialog_title => 'Report Spam?';

  @override
  String get reportSpamDialog_content =>
      'Air will be notified that this person may be sending spam. Air is never able to see the contents of any chats.';

  @override
  String get reportSpamDialog_cancel => 'Cancel';

  @override
  String get reportSpamDialog_reportSpam => 'Report Spam';

  @override
  String get reportSpamDialog_success => 'Spam reported';

  @override
  String get reportSpamDialog_error =>
      'Failed to report spam. Please try again.';

  @override
  String get helpScreen_title => 'Help';

  @override
  String get helpScreen_contactUs => 'Contact Us';

  @override
  String get helpScreen_versionInfo => 'Version Info';

  @override
  String get helpScreen_licenses => 'Licenses';

  @override
  String get licensesScreen_title => 'Licenses';

  @override
  String get contactUsScreen_title => 'Contact';

  @override
  String get contactUsScreen_subject => 'Message subject';

  @override
  String get contactUsScreen_body => 'Body';

  @override
  String get contactUsScreen_composeEmail => 'Compose Email';

  @override
  String get contactUsScreen_subject_somethingNotWorking =>
      'Something\'s not working';

  @override
  String get contactUsScreen_subject_iHaveAQuestion => 'I have a question';

  @override
  String get contactUsScreen_subject_requestFeature => 'Request a feature';

  @override
  String get contactUsScreen_subject_other => 'Other';

  @override
  String get contactUsScreen_subject_empty => 'Please select a subject';

  @override
  String get contactUsScreen_body_empty => 'Enter your message';

  @override
  String get contactUsScreen_body_tooShort => 'Please provide more information';

  @override
  String get contactUsScreen_errorLaunchingEmail =>
      'Could not launch email client';

  @override
  String get groupDetails_members => 'Members';

  @override
  String get groupDetails_addMembers => 'Add Members';

  @override
  String get groupDetails_leaveChat => 'Leave Chat';

  @override
  String get groupDetails_deleteChat => 'Delete Chat';

  @override
  String get leaveChatDialog_title => 'Leave Chat';

  @override
  String get leaveChatDialog_content =>
      'Are you sure you want to leave this chat?';

  @override
  String get leaveChatDialog_cancel => 'Cancel';

  @override
  String get leaveChatDialog_leave => 'Leave';

  @override
  String get deleteChatDialog_title => 'Delete Chat';

  @override
  String get deleteChatDialog_content =>
      'Are you sure you want to delete this chat? The message history will be also deleted.';

  @override
  String get deleteChatDialog_cancel => 'Cancel';

  @override
  String get deleteChatDialog_delete => 'Delete';

  @override
  String get byteUnit_B => 'B';

  @override
  String get byteUnit_KB => 'KB';

  @override
  String get byteUnit_MB => 'MB';

  @override
  String get byteUnit_GB => 'GB';

  @override
  String get byteUnit_TB => 'TB';

  @override
  String get byteUnit_PB => 'PB';

  @override
  String get byteUnit_EB => 'EB';

  @override
  String get byteUnit_ZB => 'ZB';

  @override
  String get byteUnit_YB => 'YB';
}
