// SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// This file is automatically generated, so please do not edit it.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class AppLocalizationsDe extends AppLocalizations {
  AppLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String get appTitle => 'Air';

  @override
  String get userSettingsScreen_title => 'Benutzereinstellungen';

  @override
  String get userSettingsScreen_idCopied =>
      'Benutzer-ID in Zwischenablage kopiert';

  @override
  String get userSettingsScreen_profileDescription =>
      'Andere sehen dein Bild und deinen Namen, wenn du mit ihnen kommunizierst.';

  @override
  String get userSettingsScreen_userNamesDescription =>
      'Teile Benutzernamen mit anderen, damit sie sich mit dir verbinden können. Nach der Verbindung sind Benutzernamen für andere nicht mehr sichtbar. Du kannst bis zu 5 Benutzernamen haben.';

  @override
  String get userSettingsScreen_interfaceScale => 'Oberflächenskalierung';

  @override
  String get userSettingsScreen_help => 'Hilfe';

  @override
  String get removeUsernameDialog_title => 'Benutzername entfernen';

  @override
  String get removeUsernameDialog_content =>
      'Wenn du fortfährst, wird dein Benutzername entfernt und kann von jemand anderem beansprucht werden. Du wirst über ihn nicht mehr erreichbar sein.';

  @override
  String get removeUsernameDialog_cancel => 'Abbrechen';

  @override
  String get removeUsernameDialog_remove => 'Entfernen';

  @override
  String get userSettingsScreen_noUserHandles => 'noch keine Benutzernamen';

  @override
  String get userSettingsScreen_userHandlePlaceholder => 'Benutzername';

  @override
  String get addMembersScreen_title => 'Mitglieder hinzufügen';

  @override
  String get addMembersScreen_addMembers => 'Mitglied(er) hinzufügen';

  @override
  String get addMembersScreen_error_noActiveConversation =>
      'eine aktive Unterhaltung ist erforderlich';

  @override
  String get conversationDetailsScreen_title => 'Details';

  @override
  String get conversationDetailsScreen_unknownConversation =>
      'Unbekannte Unterhaltung';

  @override
  String get conversationScreen_emptyConversation =>
      'Wähle eine Unterhaltung aus, um mit dem Nachrichten schreiben zu beginnen';

  @override
  String get memberDetailsScreen_title => 'Mitgliederdetails';

  @override
  String get removeUserDialog_title => 'Benutzer entfernen';

  @override
  String get removeUserDialog_content =>
      'Bist du sicher, dass du diesen Benutzer aus der Gruppe entfernen möchtest?';

  @override
  String get removeUserDialog_cancel => 'Abbrechen';

  @override
  String get removeUserDialog_removeUser => 'Benutzer entfernen';

  @override
  String get removeUserButton_text => 'Benutzer entfernen';

  @override
  String get deleteConnectionButton_text => 'Delete Connection';

  @override
  String get deleteConnectionDialog_title => 'Delete Connection';

  @override
  String get deleteConnectionDialog_content =>
      'Are you sure you want to delete this connection? The message history will be also deleted.';

  @override
  String get deleteConnectionDialog_cancel => 'Cancel';

  @override
  String get deleteConnectionDialog_delete => 'Delete';

  @override
  String get introScreen_signUp => 'Registrieren';

  @override
  String get userHandleScreen_title => 'Benutzername';

  @override
  String get userHandleScreen_inputHint => 'Benutzername';

  @override
  String get userHandleScreen_error_emptyHandle =>
      'Benutzername darf nicht leer sein';

  @override
  String get userHandleScreen_description =>
      'Wähle einen Benutzernamen, den andere verwenden können, um sich mit dir zu verbinden.\n\nVerwende Buchstaben, Zahlen oder Unterstriche. Mindestens 5 Zeichen.';

  @override
  String get userHandleScreen_save => 'Speichern';

  @override
  String get editDisplayNameScreen_title => 'Anzeigename';

  @override
  String get editDisplayNameScreen_hintText => 'Anzeigename';

  @override
  String get editDisplayNameScreen_description =>
      'Wähle einen Namen, den andere sehen werden, wenn du mit ihnen kommunizierst.';

  @override
  String get editDisplayNameScreen_save => 'Speichern';

  @override
  String get systemMessage_userAddedUser_prefix => '';

  @override
  String get systemMessage_userAddedUser_infix => ' hat ';

  @override
  String get systemMessage_userAddedUser_suffix => ' hinzugefügt';

  @override
  String get systemMessage_userRemovedUser_prefix => '';

  @override
  String get systemMessage_userRemovedUser_infix => ' hat ';

  @override
  String get systemMessage_userRemovedUser_suffix => ' entfernt';

  @override
  String get timestamp_now => 'Jetzt';

  @override
  String get timestamp_yesterday => 'Gestern';

  @override
  String get conversationList_newContact => 'Neuer Kontakt';

  @override
  String get conversationList_newGroup => 'Neue Gruppe';

  @override
  String get conversationList_emptyMessage =>
      'Erstelle eine neue Verbindung, um zu beginnen';

  @override
  String get conversationList_draft => 'Entwurf';

  @override
  String get conversationList_you => 'Du';

  @override
  String get conversationList_imageEmoji => '🖼️';

  @override
  String get conversationList_fileEmoji => '📎';

  @override
  String get settings_profile => 'Profil';

  @override
  String get settings_developerSettings => 'Einstellungen (Entwickler)';

  @override
  String get newConversationDialog_newConversationTitle => 'Neue Unterhaltung';

  @override
  String get newConversationDialog_newConversationDescription =>
      'Wähle einen Namen für die neue Unterhaltung';

  @override
  String get newConversationDialog_conversationNamePlaceholder =>
      'Unterhaltungsname';

  @override
  String get newConversationDialog_actionButton => 'Unterhaltung erstellen';

  @override
  String newConversationDialog_error(Object conversationName) {
    return 'Unterhaltung mit Name $conversationName konnte nicht hinzugefügt werden';
  }

  @override
  String get newConversationDialog_error_emptyGroupName =>
      'Unterhaltungsname darf nicht leer sein';

  @override
  String get newConnectionDialog_newConnectionTitle => 'Neue Verbindung';

  @override
  String get newConnectionDialog_newConnectionDescription =>
      'Gib den Benutzernamen des Benutzers ein, mit dem du dich verbinden möchtest';

  @override
  String get newConnectionDialog_usernamePlaceholder => 'Benutzername';

  @override
  String get newConnectionDialog_actionButton => 'Verbinden';

  @override
  String newConnectionDialog_error(Object username) {
    return 'Benutzer mit Benutzername $username konnte nicht hinzugefügt werden. Bitte versuche es erneut.';
  }

  @override
  String get newConnectionDialog_error_emptyHandle =>
      'Benutzername darf nicht leer sein';

  @override
  String newConnectionDialog_error_handleNotFound(Object username) {
    return 'Benutzername $username existiert nicht';
  }

  @override
  String composer_inputHint(Object conversationTitle) {
    return 'Nachricht an $conversationTitle';
  }

  @override
  String get composer_editMessage => 'Nachricht bearbeiten';

  @override
  String get composer_error_attachment =>
      'Anhang konnte nicht hochgeladen werden. Bitte versuche es erneut.';

  @override
  String attachmentSize(double size, Object byteUnit) {
    final intl.NumberFormat sizeNumberFormat = intl
        .NumberFormat.decimalPatternDigits(
      locale: localeName,
      decimalDigits: 2,
    );
    final String sizeString = sizeNumberFormat.format(size);

    return '$sizeString $byteUnit';
  }

  @override
  String get textMessage_edited => 'bearbeitet';

  @override
  String get reportSpamButton_text => 'Spam melden';

  @override
  String get reportSpamDialog_title => 'Spam melden?';

  @override
  String get reportSpamDialog_content =>
      'Air wird benachrichtigt, dass diese Person möglicherweise Spam sendet. Air kann niemals den Inhalt von Chats einsehen.';

  @override
  String get reportSpamDialog_cancel => 'Abbrechen';

  @override
  String get reportSpamDialog_reportSpam => 'Spam melden';

  @override
  String get reportSpamDialog_success => 'Spam gemeldet';

  @override
  String get reportSpamDialog_error =>
      'Spam konnte nicht gemeldet werden. Bitte versuche es erneut.';

  @override
  String get helpScreen_title => 'Hilfe';

  @override
  String get helpScreen_contactUs => 'Kontakt';

  @override
  String get helpScreen_versionInfo => 'Versionsinformationen';

  @override
  String get helpScreen_licenses => 'Lizenzen';

  @override
  String get licensesScreen_title => 'Lizenzen';

  @override
  String get contactUsScreen_title => 'Kontakt';

  @override
  String get contactUsScreen_subject => 'Nachrichtenbetreff';

  @override
  String get contactUsScreen_body => 'Inhalt';

  @override
  String get contactUsScreen_composeEmail => 'E-Mail verfassen';

  @override
  String get contactUsScreen_subject_somethingNotWorking =>
      'Etwas funktioniert nicht';

  @override
  String get contactUsScreen_subject_iHaveAQuestion => 'Ich habe eine Frage';

  @override
  String get contactUsScreen_subject_requestFeature => 'Feature anfragen';

  @override
  String get contactUsScreen_subject_other => 'Andere';

  @override
  String get contactUsScreen_subject_empty => 'Bitte wähle einen Betreff aus';

  @override
  String get contactUsScreen_body_empty => 'Gib deine Nachricht ein';

  @override
  String get contactUsScreen_body_tooShort => 'Bitte gib mehr Informationen an';

  @override
  String get contactUsScreen_errorLaunchingEmail =>
      'E-Mail-Client konnte nicht geöffnet werden';

  @override
  String get groupDetails_members => 'Members';

  @override
  String get groupDetails_addMembers => 'Add Members';

  @override
  String get groupDetails_leaveConversation => 'Leave Conversation';

  @override
  String get groupDetails_deleteConversation => 'Delete Conversation';

  @override
  String get leaveConversationDialog_title => 'Leave Conversation';

  @override
  String get leaveConversationDialog_content =>
      'Are you sure you want to leave this conversation?';

  @override
  String get leaveConversationDialog_cancel => 'Cancel';

  @override
  String get leaveConversationDialog_leave => 'Leave';

  @override
  String get deleteConversationDialog_title => 'Delete Conversation';

  @override
  String get deleteConversationDialog_content =>
      'Are you sure you want to delete this conversation? The message history will be also deleted.';

  @override
  String get deleteConversationDialog_cancel => 'Cancel';

  @override
  String get deleteConversationDialog_delete => 'Delete';

  @override
  String get byteUnit_B => 'B';

  @override
  String get byteUnit_KB => 'KB';

  @override
  String get byteUnit_MB => 'MB';

  @override
  String get byteUnit_GB => 'GB';

  @override
  String get byteUnit_TB => 'TB';

  @override
  String get byteUnit_PB => 'PB';

  @override
  String get byteUnit_EB => 'EB';

  @override
  String get byteUnit_ZB => 'ZB';

  @override
  String get byteUnit_YB => 'YB';
}
