// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors
import 'package:convert/convert.dart';

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/conversation_details_cubit.dart';
import 'api/conversation_list_cubit.dart';
import 'api/logging.dart';
import 'api/markdown.dart';
import 'api/message_cubit.dart';
import 'api/message_list_cubit.dart';
import 'api/navigation_cubit.dart';
import 'api/notifications.dart';
import 'api/types.dart';
import 'api/user.dart';
import 'api/user_cubit.dart';
import 'api/utils.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'notifications.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:uuid/uuid.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ConversationDetailsCubitBasePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ConversationListCubitBasePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_DartNotificationServicePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LogWriterPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MessageCubitBasePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MessageListCubitBasePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MessageListStatePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NavigationCubitBasePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UiRoomStatePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_UiUserPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_UserPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UserCubitBasePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ConversationDetailsCubitBase
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    dynamic raw,
  );

  @protected
  ConversationListCubitBase
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    dynamic raw,
  );

  @protected
  DartNotificationService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    dynamic raw,
  );

  @protected
  LogWriter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    dynamic raw,
  );

  @protected
  MessageCubitBase
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    dynamic raw,
  );

  @protected
  MessageListCubitBase
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    dynamic raw,
  );

  @protected
  MessageListState
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    dynamic raw,
  );

  @protected
  NavigationCubitBase
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    dynamic raw,
  );

  @protected
  UiRoomState
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    dynamic raw,
  );

  @protected
  UiUser
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    dynamic raw,
  );

  @protected
  User
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    dynamic raw,
  );

  @protected
  UserCubitBase
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    dynamic raw,
  );

  @protected
  ConversationDetailsCubitBase
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    dynamic raw,
  );

  @protected
  ConversationListCubitBase
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    dynamic raw,
  );

  @protected
  MessageCubitBase
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    dynamic raw,
  );

  @protected
  MessageListCubitBase
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    dynamic raw,
  );

  @protected
  NavigationCubitBase
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    dynamic raw,
  );

  @protected
  UserCubitBase
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    dynamic raw,
  );

  @protected
  ConversationDetailsCubitBase
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    dynamic raw,
  );

  @protected
  ConversationListCubitBase
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    dynamic raw,
  );

  @protected
  DartNotificationService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    dynamic raw,
  );

  @protected
  LogWriter
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    dynamic raw,
  );

  @protected
  MessageCubitBase
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    dynamic raw,
  );

  @protected
  MessageListCubitBase
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    dynamic raw,
  );

  @protected
  MessageListState
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    dynamic raw,
  );

  @protected
  NavigationCubitBase
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    dynamic raw,
  );

  @protected
  UiRoomState
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    dynamic raw,
  );

  @protected
  UiUser
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    dynamic raw,
  );

  @protected
  User
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    dynamic raw,
  );

  @protected
  UserCubitBase
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    dynamic raw,
  );

  @protected
  int dco_decode_CastedPrimitive_usize(dynamic raw);

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  FutureOr<List<NotificationHandle>> Function()
  dco_decode_DartFn_Inputs__Output_list_notification_handle_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(List<NotificationId>)
  dco_decode_DartFn_Inputs_list_notification_id_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(NotificationContent)
  dco_decode_DartFn_Inputs_notification_content_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  ConversationDetailsCubitBase
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    dynamic raw,
  );

  @protected
  ConversationListCubitBase
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    dynamic raw,
  );

  @protected
  DartNotificationService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    dynamic raw,
  );

  @protected
  LogWriter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    dynamic raw,
  );

  @protected
  MessageCubitBase
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    dynamic raw,
  );

  @protected
  MessageListCubitBase
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    dynamic raw,
  );

  @protected
  MessageListState
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    dynamic raw,
  );

  @protected
  NavigationCubitBase
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    dynamic raw,
  );

  @protected
  UiRoomState
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    dynamic raw,
  );

  @protected
  UiUser
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    dynamic raw,
  );

  @protected
  User
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    dynamic raw,
  );

  @protected
  UserCubitBase
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    dynamic raw,
  );

  @protected
  RustStreamSink<MessageListState>
  dco_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<UiUser>
  dco_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ConversationDetailsState>
  dco_decode_StreamSink_conversation_details_state_Sse(dynamic raw);

  @protected
  RustStreamSink<ConversationListState>
  dco_decode_StreamSink_conversation_list_state_Sse(dynamic raw);

  @protected
  RustStreamSink<LogEntry> dco_decode_StreamSink_log_entry_Sse(dynamic raw);

  @protected
  RustStreamSink<MessageState> dco_decode_StreamSink_message_state_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<NavigationState> dco_decode_StreamSink_navigation_state_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  AppState dco_decode_app_state(dynamic raw);

  @protected
  BlockElement dco_decode_block_element(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  UiRoomState
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    dynamic raw,
  );

  @protected
  User
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    dynamic raw,
  );

  @protected
  ConversationId dco_decode_box_autoadd_conversation_id(dynamic raw);

  @protected
  ConversationMessageId dco_decode_box_autoadd_conversation_message_id(
    dynamic raw,
  );

  @protected
  DeveloperSettingsScreenType
  dco_decode_box_autoadd_developer_settings_screen_type(dynamic raw);

  @protected
  HomeNavigationState dco_decode_box_autoadd_home_navigation_state(dynamic raw);

  @protected
  ImageData dco_decode_box_autoadd_image_data(dynamic raw);

  @protected
  MessageState dco_decode_box_autoadd_message_state(dynamic raw);

  @protected
  PlatformPushToken dco_decode_box_autoadd_platform_push_token(dynamic raw);

  @protected
  UiConversationDetails dco_decode_box_autoadd_ui_conversation_details(
    dynamic raw,
  );

  @protected
  UiConversationMessage dco_decode_box_autoadd_ui_conversation_message(
    dynamic raw,
  );

  @protected
  UiErrorMessage dco_decode_box_autoadd_ui_error_message(dynamic raw);

  @protected
  UiEventMessage dco_decode_box_autoadd_ui_event_message(dynamic raw);

  @protected
  UiInactiveConversation dco_decode_box_autoadd_ui_inactive_conversation(
    dynamic raw,
  );

  @protected
  UiSystemMessage dco_decode_box_autoadd_ui_system_message(dynamic raw);

  @protected
  UiUserHandle dco_decode_box_autoadd_ui_user_handle(dynamic raw);

  @protected
  UiUserId dco_decode_box_autoadd_ui_user_id(dynamic raw);

  @protected
  UiUserProfile dco_decode_box_autoadd_ui_user_profile(dynamic raw);

  @protected
  UserSettingsScreenType dco_decode_box_autoadd_user_settings_screen_type(
    dynamic raw,
  );

  @protected
  UiContentMessage dco_decode_box_ui_content_message(dynamic raw);

  @protected
  ConversationDetailsState dco_decode_conversation_details_state(dynamic raw);

  @protected
  ConversationId dco_decode_conversation_id(dynamic raw);

  @protected
  ConversationListState dco_decode_conversation_list_state(dynamic raw);

  @protected
  ConversationMessageId dco_decode_conversation_message_id(dynamic raw);

  @protected
  DeveloperSettingsScreenType dco_decode_developer_settings_screen_type(
    dynamic raw,
  );

  @protected
  HomeNavigationState dco_decode_home_navigation_state(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageData dco_decode_image_data(dynamic raw);

  @protected
  InlineElement dco_decode_inline_element(dynamic raw);

  @protected
  IntroScreenType dco_decode_intro_screen_type(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<IntroScreenType> dco_decode_list_intro_screen_type(dynamic raw);

  @protected
  List<List<List<RangedBlockElement>>>
  dco_decode_list_list_list_ranged_block_element(dynamic raw);

  @protected
  List<List<RangedBlockElement>> dco_decode_list_list_ranged_block_element(
    dynamic raw,
  );

  @protected
  List<NotificationHandle> dco_decode_list_notification_handle(dynamic raw);

  @protected
  List<NotificationId> dco_decode_list_notification_id(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RangedBlockElement> dco_decode_list_ranged_block_element(dynamic raw);

  @protected
  List<RangedCodeBlock> dco_decode_list_ranged_code_block(dynamic raw);

  @protected
  List<RangedInlineElement> dco_decode_list_ranged_inline_element(dynamic raw);

  @protected
  List<UiClientRecord> dco_decode_list_ui_client_record(dynamic raw);

  @protected
  List<UiContact> dco_decode_list_ui_contact(dynamic raw);

  @protected
  List<UiConversationDetails> dco_decode_list_ui_conversation_details(
    dynamic raw,
  );

  @protected
  List<UiUserHandle> dco_decode_list_ui_user_handle(dynamic raw);

  @protected
  List<UiUserId> dco_decode_list_ui_user_id(dynamic raw);

  @protected
  LogEntry dco_decode_log_entry(dynamic raw);

  @protected
  LogEntryLevel dco_decode_log_entry_level(dynamic raw);

  @protected
  MessageContent dco_decode_message_content(dynamic raw);

  @protected
  MessageState dco_decode_message_state(dynamic raw);

  @protected
  NavigationState dco_decode_navigation_state(dynamic raw);

  @protected
  NotificationContent dco_decode_notification_content(dynamic raw);

  @protected
  NotificationHandle dco_decode_notification_handle(dynamic raw);

  @protected
  NotificationId dco_decode_notification_id(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_usize(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  UiRoomState?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    dynamic raw,
  );

  @protected
  User?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    dynamic raw,
  );

  @protected
  ConversationId? dco_decode_opt_box_autoadd_conversation_id(dynamic raw);

  @protected
  DeveloperSettingsScreenType?
  dco_decode_opt_box_autoadd_developer_settings_screen_type(dynamic raw);

  @protected
  ImageData? dco_decode_opt_box_autoadd_image_data(dynamic raw);

  @protected
  PlatformPushToken? dco_decode_opt_box_autoadd_platform_push_token(
    dynamic raw,
  );

  @protected
  UiConversationDetails? dco_decode_opt_box_autoadd_ui_conversation_details(
    dynamic raw,
  );

  @protected
  UiConversationMessage? dco_decode_opt_box_autoadd_ui_conversation_message(
    dynamic raw,
  );

  @protected
  UiUserId? dco_decode_opt_box_autoadd_ui_user_id(dynamic raw);

  @protected
  UserSettingsScreenType? dco_decode_opt_box_autoadd_user_settings_screen_type(
    dynamic raw,
  );

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PlatformPushToken dco_decode_platform_push_token(dynamic raw);

  @protected
  RangedBlockElement dco_decode_ranged_block_element(dynamic raw);

  @protected
  RangedCodeBlock dco_decode_ranged_code_block(dynamic raw);

  @protected
  RangedInlineElement dco_decode_ranged_inline_element(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiClientRecord dco_decode_ui_client_record(dynamic raw);

  @protected
  UiContact dco_decode_ui_contact(dynamic raw);

  @protected
  UiContentMessage dco_decode_ui_content_message(dynamic raw);

  @protected
  UiConversationAttributes dco_decode_ui_conversation_attributes(dynamic raw);

  @protected
  UiConversationDetails dco_decode_ui_conversation_details(dynamic raw);

  @protected
  UiConversationMessage dco_decode_ui_conversation_message(dynamic raw);

  @protected
  UiConversationStatus dco_decode_ui_conversation_status(dynamic raw);

  @protected
  UiConversationType dco_decode_ui_conversation_type(dynamic raw);

  @protected
  UiErrorMessage dco_decode_ui_error_message(dynamic raw);

  @protected
  UiEventMessage dco_decode_ui_event_message(dynamic raw);

  @protected
  UiFlightPosition dco_decode_ui_flight_position(dynamic raw);

  @protected
  UiInactiveConversation dco_decode_ui_inactive_conversation(dynamic raw);

  @protected
  UiMessage dco_decode_ui_message(dynamic raw);

  @protected
  UiMimiContent dco_decode_ui_mimi_content(dynamic raw);

  @protected
  UiSystemMessage dco_decode_ui_system_message(dynamic raw);

  @protected
  UiUserHandle dco_decode_ui_user_handle(dynamic raw);

  @protected
  UiUserId dco_decode_ui_user_id(dynamic raw);

  @protected
  UiUserProfile dco_decode_ui_user_profile(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserSettingsScreenType dco_decode_user_settings_screen_type(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ConversationDetailsCubitBase
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  ConversationListCubitBase
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  DartNotificationService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    SseDeserializer deserializer,
  );

  @protected
  LogWriter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    SseDeserializer deserializer,
  );

  @protected
  MessageCubitBase
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  MessageListCubitBase
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  MessageListState
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    SseDeserializer deserializer,
  );

  @protected
  NavigationCubitBase
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  UiRoomState
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    SseDeserializer deserializer,
  );

  @protected
  UiUser
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    SseDeserializer deserializer,
  );

  @protected
  User
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    SseDeserializer deserializer,
  );

  @protected
  UserCubitBase
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDetailsCubitBase
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  ConversationListCubitBase
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  MessageCubitBase
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  MessageListCubitBase
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  NavigationCubitBase
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  UserCubitBase
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDetailsCubitBase
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  ConversationListCubitBase
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  DartNotificationService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    SseDeserializer deserializer,
  );

  @protected
  LogWriter
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    SseDeserializer deserializer,
  );

  @protected
  MessageCubitBase
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  MessageListCubitBase
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  MessageListState
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    SseDeserializer deserializer,
  );

  @protected
  NavigationCubitBase
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  UiRoomState
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    SseDeserializer deserializer,
  );

  @protected
  UiUser
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    SseDeserializer deserializer,
  );

  @protected
  User
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    SseDeserializer deserializer,
  );

  @protected
  UserCubitBase
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  ConversationDetailsCubitBase
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  ConversationListCubitBase
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  DartNotificationService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    SseDeserializer deserializer,
  );

  @protected
  LogWriter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    SseDeserializer deserializer,
  );

  @protected
  MessageCubitBase
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  MessageListCubitBase
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  MessageListState
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    SseDeserializer deserializer,
  );

  @protected
  NavigationCubitBase
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  UiRoomState
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    SseDeserializer deserializer,
  );

  @protected
  UiUser
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    SseDeserializer deserializer,
  );

  @protected
  User
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    SseDeserializer deserializer,
  );

  @protected
  UserCubitBase
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MessageListState>
  sse_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<UiUser>
  sse_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ConversationDetailsState>
  sse_decode_StreamSink_conversation_details_state_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ConversationListState>
  sse_decode_StreamSink_conversation_list_state_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogEntry> sse_decode_StreamSink_log_entry_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MessageState> sse_decode_StreamSink_message_state_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<NavigationState> sse_decode_StreamSink_navigation_state_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  AppState sse_decode_app_state(SseDeserializer deserializer);

  @protected
  BlockElement sse_decode_block_element(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  UiRoomState
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    SseDeserializer deserializer,
  );

  @protected
  User
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    SseDeserializer deserializer,
  );

  @protected
  ConversationId sse_decode_box_autoadd_conversation_id(
    SseDeserializer deserializer,
  );

  @protected
  ConversationMessageId sse_decode_box_autoadd_conversation_message_id(
    SseDeserializer deserializer,
  );

  @protected
  DeveloperSettingsScreenType
  sse_decode_box_autoadd_developer_settings_screen_type(
    SseDeserializer deserializer,
  );

  @protected
  HomeNavigationState sse_decode_box_autoadd_home_navigation_state(
    SseDeserializer deserializer,
  );

  @protected
  ImageData sse_decode_box_autoadd_image_data(SseDeserializer deserializer);

  @protected
  MessageState sse_decode_box_autoadd_message_state(
    SseDeserializer deserializer,
  );

  @protected
  PlatformPushToken sse_decode_box_autoadd_platform_push_token(
    SseDeserializer deserializer,
  );

  @protected
  UiConversationDetails sse_decode_box_autoadd_ui_conversation_details(
    SseDeserializer deserializer,
  );

  @protected
  UiConversationMessage sse_decode_box_autoadd_ui_conversation_message(
    SseDeserializer deserializer,
  );

  @protected
  UiErrorMessage sse_decode_box_autoadd_ui_error_message(
    SseDeserializer deserializer,
  );

  @protected
  UiEventMessage sse_decode_box_autoadd_ui_event_message(
    SseDeserializer deserializer,
  );

  @protected
  UiInactiveConversation sse_decode_box_autoadd_ui_inactive_conversation(
    SseDeserializer deserializer,
  );

  @protected
  UiSystemMessage sse_decode_box_autoadd_ui_system_message(
    SseDeserializer deserializer,
  );

  @protected
  UiUserHandle sse_decode_box_autoadd_ui_user_handle(
    SseDeserializer deserializer,
  );

  @protected
  UiUserId sse_decode_box_autoadd_ui_user_id(SseDeserializer deserializer);

  @protected
  UiUserProfile sse_decode_box_autoadd_ui_user_profile(
    SseDeserializer deserializer,
  );

  @protected
  UserSettingsScreenType sse_decode_box_autoadd_user_settings_screen_type(
    SseDeserializer deserializer,
  );

  @protected
  UiContentMessage sse_decode_box_ui_content_message(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDetailsState sse_decode_conversation_details_state(
    SseDeserializer deserializer,
  );

  @protected
  ConversationId sse_decode_conversation_id(SseDeserializer deserializer);

  @protected
  ConversationListState sse_decode_conversation_list_state(
    SseDeserializer deserializer,
  );

  @protected
  ConversationMessageId sse_decode_conversation_message_id(
    SseDeserializer deserializer,
  );

  @protected
  DeveloperSettingsScreenType sse_decode_developer_settings_screen_type(
    SseDeserializer deserializer,
  );

  @protected
  HomeNavigationState sse_decode_home_navigation_state(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageData sse_decode_image_data(SseDeserializer deserializer);

  @protected
  InlineElement sse_decode_inline_element(SseDeserializer deserializer);

  @protected
  IntroScreenType sse_decode_intro_screen_type(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<IntroScreenType> sse_decode_list_intro_screen_type(
    SseDeserializer deserializer,
  );

  @protected
  List<List<List<RangedBlockElement>>>
  sse_decode_list_list_list_ranged_block_element(SseDeserializer deserializer);

  @protected
  List<List<RangedBlockElement>> sse_decode_list_list_ranged_block_element(
    SseDeserializer deserializer,
  );

  @protected
  List<NotificationHandle> sse_decode_list_notification_handle(
    SseDeserializer deserializer,
  );

  @protected
  List<NotificationId> sse_decode_list_notification_id(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RangedBlockElement> sse_decode_list_ranged_block_element(
    SseDeserializer deserializer,
  );

  @protected
  List<RangedCodeBlock> sse_decode_list_ranged_code_block(
    SseDeserializer deserializer,
  );

  @protected
  List<RangedInlineElement> sse_decode_list_ranged_inline_element(
    SseDeserializer deserializer,
  );

  @protected
  List<UiClientRecord> sse_decode_list_ui_client_record(
    SseDeserializer deserializer,
  );

  @protected
  List<UiContact> sse_decode_list_ui_contact(SseDeserializer deserializer);

  @protected
  List<UiConversationDetails> sse_decode_list_ui_conversation_details(
    SseDeserializer deserializer,
  );

  @protected
  List<UiUserHandle> sse_decode_list_ui_user_handle(
    SseDeserializer deserializer,
  );

  @protected
  List<UiUserId> sse_decode_list_ui_user_id(SseDeserializer deserializer);

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer);

  @protected
  LogEntryLevel sse_decode_log_entry_level(SseDeserializer deserializer);

  @protected
  MessageContent sse_decode_message_content(SseDeserializer deserializer);

  @protected
  MessageState sse_decode_message_state(SseDeserializer deserializer);

  @protected
  NavigationState sse_decode_navigation_state(SseDeserializer deserializer);

  @protected
  NotificationContent sse_decode_notification_content(
    SseDeserializer deserializer,
  );

  @protected
  NotificationHandle sse_decode_notification_handle(
    SseDeserializer deserializer,
  );

  @protected
  NotificationId sse_decode_notification_id(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_usize(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  UiRoomState?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    SseDeserializer deserializer,
  );

  @protected
  User?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    SseDeserializer deserializer,
  );

  @protected
  ConversationId? sse_decode_opt_box_autoadd_conversation_id(
    SseDeserializer deserializer,
  );

  @protected
  DeveloperSettingsScreenType?
  sse_decode_opt_box_autoadd_developer_settings_screen_type(
    SseDeserializer deserializer,
  );

  @protected
  ImageData? sse_decode_opt_box_autoadd_image_data(
    SseDeserializer deserializer,
  );

  @protected
  PlatformPushToken? sse_decode_opt_box_autoadd_platform_push_token(
    SseDeserializer deserializer,
  );

  @protected
  UiConversationDetails? sse_decode_opt_box_autoadd_ui_conversation_details(
    SseDeserializer deserializer,
  );

  @protected
  UiConversationMessage? sse_decode_opt_box_autoadd_ui_conversation_message(
    SseDeserializer deserializer,
  );

  @protected
  UiUserId? sse_decode_opt_box_autoadd_ui_user_id(SseDeserializer deserializer);

  @protected
  UserSettingsScreenType? sse_decode_opt_box_autoadd_user_settings_screen_type(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PlatformPushToken sse_decode_platform_push_token(
    SseDeserializer deserializer,
  );

  @protected
  RangedBlockElement sse_decode_ranged_block_element(
    SseDeserializer deserializer,
  );

  @protected
  RangedCodeBlock sse_decode_ranged_code_block(SseDeserializer deserializer);

  @protected
  RangedInlineElement sse_decode_ranged_inline_element(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiClientRecord sse_decode_ui_client_record(SseDeserializer deserializer);

  @protected
  UiContact sse_decode_ui_contact(SseDeserializer deserializer);

  @protected
  UiContentMessage sse_decode_ui_content_message(SseDeserializer deserializer);

  @protected
  UiConversationAttributes sse_decode_ui_conversation_attributes(
    SseDeserializer deserializer,
  );

  @protected
  UiConversationDetails sse_decode_ui_conversation_details(
    SseDeserializer deserializer,
  );

  @protected
  UiConversationMessage sse_decode_ui_conversation_message(
    SseDeserializer deserializer,
  );

  @protected
  UiConversationStatus sse_decode_ui_conversation_status(
    SseDeserializer deserializer,
  );

  @protected
  UiConversationType sse_decode_ui_conversation_type(
    SseDeserializer deserializer,
  );

  @protected
  UiErrorMessage sse_decode_ui_error_message(SseDeserializer deserializer);

  @protected
  UiEventMessage sse_decode_ui_event_message(SseDeserializer deserializer);

  @protected
  UiFlightPosition sse_decode_ui_flight_position(SseDeserializer deserializer);

  @protected
  UiInactiveConversation sse_decode_ui_inactive_conversation(
    SseDeserializer deserializer,
  );

  @protected
  UiMessage sse_decode_ui_message(SseDeserializer deserializer);

  @protected
  UiMimiContent sse_decode_ui_mimi_content(SseDeserializer deserializer);

  @protected
  UiSystemMessage sse_decode_ui_system_message(SseDeserializer deserializer);

  @protected
  UiUserHandle sse_decode_ui_user_handle(SseDeserializer deserializer);

  @protected
  UiUserId sse_decode_ui_user_id(SseDeserializer deserializer);

  @protected
  UiUserProfile sse_decode_ui_user_profile(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserSettingsScreenType sse_decode_user_settings_screen_type(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    ConversationDetailsCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    ConversationListCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    DartNotificationService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    LogWriter self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    MessageCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    MessageListCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    MessageListState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    NavigationCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    UiRoomState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    UiUser self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    User self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    UserCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    ConversationDetailsCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    ConversationListCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    MessageCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    MessageListCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    NavigationCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    UserCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    ConversationDetailsCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    ConversationListCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    DartNotificationService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    LogWriter self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    MessageCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    MessageListCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    MessageListState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    NavigationCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    UiRoomState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    UiUser self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    User self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    UserCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_usize(int self, SseSerializer serializer);

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void
  sse_encode_DartFn_Inputs__Output_list_notification_handle_AnyhowException(
    FutureOr<List<NotificationHandle>> Function() self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_list_notification_id_Output_unit_AnyhowException(
    FutureOr<void> Function(List<NotificationId>) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_notification_content_Output_unit_AnyhowException(
    FutureOr<void> Function(NotificationContent) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    ConversationDetailsCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    ConversationListCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    DartNotificationService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    LogWriter self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    MessageCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    MessageListCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    MessageListState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    NavigationCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    UiRoomState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    UiUser self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    User self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    UserCubitBase self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState_Sse(
    RustStreamSink<MessageListState> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser_Sse(
    RustStreamSink<UiUser> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_conversation_details_state_Sse(
    RustStreamSink<ConversationDetailsState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_conversation_list_state_Sse(
    RustStreamSink<ConversationListState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_entry_Sse(
    RustStreamSink<LogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_message_state_Sse(
    RustStreamSink<MessageState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_navigation_state_Sse(
    RustStreamSink<NavigationState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_app_state(AppState self, SseSerializer serializer);

  @protected
  void sse_encode_block_element(BlockElement self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    UiRoomState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    User self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_conversation_id(
    ConversationId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_conversation_message_id(
    ConversationMessageId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_developer_settings_screen_type(
    DeveloperSettingsScreenType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_home_navigation_state(
    HomeNavigationState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_image_data(
    ImageData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_message_state(
    MessageState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_platform_push_token(
    PlatformPushToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_conversation_details(
    UiConversationDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_conversation_message(
    UiConversationMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_error_message(
    UiErrorMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_event_message(
    UiEventMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_inactive_conversation(
    UiInactiveConversation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_system_message(
    UiSystemMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_user_handle(
    UiUserHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_user_id(
    UiUserId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_user_profile(
    UiUserProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_user_settings_screen_type(
    UserSettingsScreenType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_ui_content_message(
    UiContentMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_details_state(
    ConversationDetailsState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_id(
    ConversationId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_list_state(
    ConversationListState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_message_id(
    ConversationMessageId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_developer_settings_screen_type(
    DeveloperSettingsScreenType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_home_navigation_state(
    HomeNavigationState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_data(ImageData self, SseSerializer serializer);

  @protected
  void sse_encode_inline_element(InlineElement self, SseSerializer serializer);

  @protected
  void sse_encode_intro_screen_type(
    IntroScreenType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_intro_screen_type(
    List<IntroScreenType> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_list_ranged_block_element(
    List<List<List<RangedBlockElement>>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_ranged_block_element(
    List<List<RangedBlockElement>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_notification_handle(
    List<NotificationHandle> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_notification_id(
    List<NotificationId> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ranged_block_element(
    List<RangedBlockElement> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ranged_code_block(
    List<RangedCodeBlock> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ranged_inline_element(
    List<RangedInlineElement> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_client_record(
    List<UiClientRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_contact(
    List<UiContact> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_conversation_details(
    List<UiConversationDetails> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_user_handle(
    List<UiUserHandle> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_user_id(
    List<UiUserId> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_log_entry_level(LogEntryLevel self, SseSerializer serializer);

  @protected
  void sse_encode_message_content(
    MessageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_state(MessageState self, SseSerializer serializer);

  @protected
  void sse_encode_navigation_state(
    NavigationState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_content(
    NotificationContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_handle(
    NotificationHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_id(
    NotificationId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_CastedPrimitive_usize(
    int? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    UiRoomState? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    User? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_conversation_id(
    ConversationId? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_developer_settings_screen_type(
    DeveloperSettingsScreenType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_image_data(
    ImageData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_platform_push_token(
    PlatformPushToken? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ui_conversation_details(
    UiConversationDetails? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ui_conversation_message(
    UiConversationMessage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ui_user_id(
    UiUserId? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_user_settings_screen_type(
    UserSettingsScreenType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_platform_push_token(
    PlatformPushToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ranged_block_element(
    RangedBlockElement self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ranged_code_block(
    RangedCodeBlock self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ranged_inline_element(
    RangedInlineElement self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_client_record(
    UiClientRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_contact(UiContact self, SseSerializer serializer);

  @protected
  void sse_encode_ui_content_message(
    UiContentMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_conversation_attributes(
    UiConversationAttributes self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_conversation_details(
    UiConversationDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_conversation_message(
    UiConversationMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_conversation_status(
    UiConversationStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_conversation_type(
    UiConversationType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_error_message(
    UiErrorMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_event_message(
    UiEventMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_flight_position(
    UiFlightPosition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_inactive_conversation(
    UiInactiveConversation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_message(UiMessage self, SseSerializer serializer);

  @protected
  void sse_encode_ui_mimi_content(UiMimiContent self, SseSerializer serializer);

  @protected
  void sse_encode_ui_system_message(
    UiSystemMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_user_handle(UiUserHandle self, SseSerializer serializer);

  @protected
  void sse_encode_ui_user_id(UiUserId self, SseSerializer serializer);

  @protected
  void sse_encode_ui_user_profile(UiUserProfile self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_settings_screen_type(
    UserSettingsScreenType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationDetailsCubitBase(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConversationListCubitBase(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartNotificationService(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogWriter(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageCubitBase(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListCubitBase(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessageListState(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNavigationCubitBase(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiRoomState(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiUser(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUser(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUserCubitBase(
    int ptr,
  );
}
