// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class LocalNotificationContent {
  final String title;
  final String body;

  const LocalNotificationContent({
    required this.title,
    required this.body,
  });

  @override
  int get hashCode => title.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalNotificationContent &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          body == other.body;
}
