// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'message_content.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'user_cubit.dart';

// These functions are ignored because they are not marked as `pub`: `attachment_downloads_loop`, `spawn_attachment_downloads`, `spawn_download_task`, `track_attachment_download`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DownloadTaskHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AttachmentsRepository>>
abstract class AttachmentsRepository implements RustOpaqueInterface {
  Future<Uint8List> loadImageAttachment({
    required AttachmentId attachmentId,
    required FutureOr<void> Function(BigInt) chunkEventCallback,
  });

  factory AttachmentsRepository({required UserCubitBase userCubit}) => RustLib
      .instance
      .api
      .crateApiAttachmentsRepositoryAttachmentsRepositoryNew(
        userCubit: userCubit,
      );
}
