// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'markdown.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'message_content.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `convert_attachment`, `error_message`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `hash`, `hash`

/// Mirror of the [`AttachmentId`] type
class AttachmentId {
  final UuidValue uuid;

  const AttachmentId({required this.uuid});

  @override
  String toString() => 'AttachmentId($uuid)';

  @override
  int get hashCode => uuid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentId &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid;
}

@freezed
sealed class UiAttachment with _$UiAttachment {
  const factory UiAttachment({
    required AttachmentId attachmentId,
    required String filename,
    required String contentType,
    String? description,
    required int size,
    String? blurhash,
  }) = _UiAttachment;
}

/// The actual content of a message
@freezed
sealed class UiMimiContent with _$UiMimiContent {
  const factory UiMimiContent({
    Uint8List? replaces,
    required Uint8List topicId,
    Uint8List? inReplyTo,
    String? plainBody,
    MessageContent? content,
    required List<UiAttachment> attachments,
  }) = _UiMimiContent;
}
