// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'types.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Callbacks`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartNavigation>>
abstract class DartNavigation implements RustOpaqueInterface {
  /// Returns the conversation ID of the currently open conversation, if any.
  Future<ConversationId?> currentConversationId();

  /// Wraps the navigation cubit from the Dart side.
  ///
  /// The provided callbacks are called on the `navigation_cubit` parameter.
  factory DartNavigation(
          {required Object navigationCubit,
          required FutureOr<ConversationId?> Function(Object)
              currentConversationCallback}) =>
      RustLib.instance.api.crateApiNavigationDartNavigationNew(
          navigationCubit: navigationCubit,
          currentConversationCallback: currentConversationCallback);
}
